language: node_js
node_js:
- 0.12.2
#- 4.1.0
install: npm install
after_success:
- npm install codeclimate-test-reporter
- cat coverage/client/lcov.info coverage/server/lcov.info | codeclimate-test-reporter
